<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Xiaomi</name>
   <tag></tag>
   <elementGuidId>90a10c6e-34b7-44b5-b7c3-da68adf87150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[3]/div[@class=&quot;css-ujyk5r&quot;]/div[@class=&quot;css-79elbk e1uu5jkk0&quot;]/div[@class=&quot;css-1yp4ln e1uu5jkk6&quot;]/div[@class=&quot;css-1e4fvq e1uu5jkk4&quot;]/div[@class=&quot;css-14jkswy&quot;]/div[@class=&quot;collapse-wrapper css-4i7nq1&quot;]/div[@class=&quot;css-12obs87&quot;]/div[@class=&quot;collapse-body css-17baliq&quot;]/div[@class=&quot;show-less css-86glef&quot;]/div[@class=&quot;css-ujyk5r&quot;]/div[@class=&quot;css-1qebmyp&quot;]/div[@class=&quot;css-tyr9st e1uu5jkk11&quot;]/label[@class=&quot;css-1y28mi8&quot;]/span[@class=&quot;css-ydlygv e1uu5jkk34&quot;]/input[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div[3]/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[9]/label/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/label/span/input</value>
   </webElementXpaths>
</WebElementEntity>
